# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-3150727-cad115/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu9eg-ffvb1156-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/7698 /opt/xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/7698 {
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v
    }
      rt::read_verilog -include /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/7698 {
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/ADD_SUB_Sharing.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/ALU.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/Controller.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/Core.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/Input_Memory.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/Instruction_Memory.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/receiver.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/transmitter.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/710b/src/Add_IP.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_Tiny_CPU_IP_0_0/synth/design_1_Tiny_CPU_IP_0_0.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/synth/design_1.v
      /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib xpm /opt/xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_25M_0/synth/design_1_rst_clk_wiz_0_25M_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3150727-cad115/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
