# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc_TinyCPU_HDH.xdc

# Block Designs: bd/design_HDH/design_HDH.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_HDH || ORIG_REF_NAME==design_HDH} -quiet] -quiet

# IP: bd/design_HDH/ip/design_HDH_Add_IP_HDH_0_0/design_HDH_Add_IP_HDH_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_HDH_Add_IP_HDH_0_0 || ORIG_REF_NAME==design_HDH_Add_IP_HDH_0_0} -quiet] -quiet

# IP: bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_HDH_clk_wiz_0_0 || ORIG_REF_NAME==design_HDH_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_HDH/ip/design_HDH_rst_clk_wiz_0_25M_0/design_HDH_rst_clk_wiz_0_25M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_HDH_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_HDH_rst_clk_wiz_0_25M_0} -quiet] -quiet

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_HDH_clk_wiz_0_0 || ORIG_REF_NAME==design_HDH_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_HDH_clk_wiz_0_0 || ORIG_REF_NAME==design_HDH_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0_ooc.xdc

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_rst_clk_wiz_0_25M_0/design_HDH_rst_clk_wiz_0_25M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_HDH_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_HDH_rst_clk_wiz_0_25M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_rst_clk_wiz_0_25M_0/design_HDH_rst_clk_wiz_0_25M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_HDH_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_HDH_rst_clk_wiz_0_25M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/design_HDH_ooc.xdc
