# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Fixed_Point_Adder/Simulation/Simulation.srcs/constrs_1/new/ct.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_25M_0/design_1_rst_clk_wiz_0_25M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_25M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Tiny_CPU_IP_0_0/design_1_Tiny_CPU_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Tiny_CPU_IP_0_0 || ORIG_REF_NAME==design_1_Tiny_CPU_IP_0_0} -quiet] -quiet

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_25M_0/design_1_rst_clk_wiz_0_25M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_25M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_25M_0/design_1_rst_clk_wiz_0_25M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_25M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_25M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/hoailuan/AISeQ/Khoa_Vi_Mach_Can_Ban/Programmable_Tiny_PE/Tiny_CPU/Tiny_CPU.gen/sources_1/bd/design_1/design_1_ooc.xdc
