set_property SRC_FILE_INFO {cfile:d:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0.xdc rfile:../../../Lab_2_Tiny_CPU.gen/sources_1/bd/design_HDH/ip/design_HDH_clk_wiz_0_0/design_HDH_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_HDH_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/HOC_TAP/Nghien_cuu_khoa_hoc/NCKH_2025/Tiny_Custom_CPU/Lab_2_Tiny_CPU/Lab_2_Tiny_CPU.srcs/constrs_1/new/xdc_TinyCPU_HDH.xdc rfile:../../../Lab_2_Tiny_CPU.srcs/constrs_1/new/xdc_TinyCPU_HDH.xdc id:2} [current_design]
current_instance design_HDH_i/clk_wiz_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.033
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports Rx_in_0]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports Tx_out_0]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL12 [get_ports {LED_out_0[7]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {LED_out_0[6]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports {LED_out_0[5]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15 [get_ports {LED_out_0[4]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14 [get_ports {LED_out_0[3]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {LED_out_0[2]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {LED_out_0[1]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {LED_out_0[0]}]
